name: Build

on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: docker login ghcr.io --username lukewarmtemp --password ${{ secrets.GH_PAT }}
      - name: Build container image
        run: docker build . --tag ghcr.io/lukewarmtemp/ros-fedora-coreos:latest
      - name: Push container image to registry
        run: docker push ghcr.io/lukewarmtemp/ros-fedora-coreos:latest
